apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-api
  namespace: {{.Release.Namespace}}
spec:
  selector:
      app: api    # Must match the selector in the deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP