# Step 2: Deployment:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-api
  namespace: {{.Release.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api  #important
      
  template:
    metadata:
      labels:
        app: api  #must match the selector
        app.kubernetes.io/managed-by: Helm
    spec:
      containers:
      - name: api
        image: "{{.Values.image.api.repository}}:{{.Values.image.api.tag}}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: {{.Release.Name}}-api-config
        # - name: MLFLOW_TRACKING_URI
        #   value: "http://mlflow:5000"
        # - name: MODEL_URI
        #   value: "models:/iris-model/latest"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        startupProbe:
          httpGet:
            path: {{.Values.probes.api.startup.path}}
            port: {{.Values.probes.api.startup.port}}
          failureThreshold: {{.Values.probes.api.startup.failureThreshold}}
          periodSeconds:  {{.Values.probes.api.startup.periodSeconds}}
          initialDelaySeconds: {{.Values.probes.api.startup.initialDelaySeconds}}
          timeoutSeconds: {{.Values.probes.api.startup.timeoutSeconds}}
        livenessProbe:
          httpGet:
            path: {{.Values.probes.api.liveness.path}}
            port: {{.Values.probes.api.liveness.port}}
          initialDelaySeconds: {{.Values.probes.api.liveness.initialDelaySeconds}}
          periodSeconds: {{.Values.probes.api.liveness.periodSeconds}}
          failureThreshold: {{.Values.probes.api.liveness.failureThreshold}}
        readinessProbe:
          httpGet:
            path: {{.Values.probes.api.readiness.path}}
            port: 8000
          initialDelaySeconds: {{.Values.probes.api.readiness.initialDelaySeconds}}
          periodSeconds: {{.Values.probes.api.readiness.periodSeconds}}
          failureThreshold: {{.Values.probes.api.readiness.failureThreshold}}