apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Release.Name}}-mlflow-pvc
  namespace: mlops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: {{.Values.pvc.size}}