apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-mlflow
  namespace: {{.Release.Namespace}}
spec:
  selector:
      app: mlflow
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP