services:

  mlflow:
    build:
      context: .
      dockerfile: mlflow/Dockerfile
    image: iris-mlflow:dev

  api:
    build:
      context: .
      dockerfile: api/Dockerfile.rootcontext
    image: iris-api:dev

  trainer:
    build:
      context: .
      dockerfile: train/Dockerfile
    image: iris-train:dev
