apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: mlops
data:
  # You can add any configuration data your API needs here. For example:
  # config.yaml: |
  #   setting1: value1
  #   setting2: value2
  MLFLOW_TRACKING_URI: "http://mlflow:5000"
  MODEL_URI: "models:/iris-model/latest"