apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      initContainers:
      - name: init-mlflow-dirs
        image: busybox
        command: ["sh", "-c", "mkdir -p /mlflow/db && mkdir -p /mlflow/artifacts"]
        volumeMounts:
        - name: mlflow-storage
          mountPath: /mlflow
      containers:
      - name: mlflow
        image: debago/iris-mlflow:IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        command: ["mlflow"]   # To override default entrypoint in the Dockerfile
        args:                 # To override default command in the Dockerfile
          - server
          - --backend-store-uri
          - sqlite:////mlflow/db/mlflow.db
          - --artifacts-destination
          - /mlflow/artifacts
          - --serve-artifacts
          - --allowed-hosts
          - "*"
          - --host
          - 0.0.0.0
          - --port
          - "5000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "800m"
        
        volumeMounts:
        - name: mlflow-storage
          mountPath: /mlflow
      
      volumes:
      - name: mlflow-storage
        persistentVolumeClaim:
          claimName: mlflow-pvc
      livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 15
          failureThreshold: 3
          