apiVersion: batch/v1
kind: Job
metadata:
  name: trainer-job
  namespace: mlops
spec:
  template:
    spec:
      containers:
      - name: trainer
        image: debago/iris-trainer:dev
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow:5000"
      restartPolicy: Never