apiVersion: batch/v1
kind: Job
metadata:
  name: trainer-job
  namespace: mlops
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: trainer
        image: debago/iris-train:IMAGE_TAG
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: trainer-config
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "600Mi"
            cpu: "400m"