name: CI-CD Multi Env Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  IMAGE_TAG: ${{ github.sha }}

jobs:

# -----------------------
# BUILD & PUSH (ONLY ONCE)
# -----------------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build API
        run: |
          docker build -t $DOCKER_USERNAME/iris-api:${IMAGE_TAG} -f api/Dockerfile .

      - name: Build Trainer
        run: |
          docker build -t $DOCKER_USERNAME/iris-train:${IMAGE_TAG} -f train/Dockerfile .
        
      - name: Build MLFLOW
        run: |
          docker build -t $DOCKER_USERNAME/iris-mlflow:${IMAGE_TAG} -f mlflow/Dockerfile .

      - name: Push Images
        run: |
          docker push $DOCKER_USERNAME/iris-api:${IMAGE_TAG}
          docker push $DOCKER_USERNAME/iris-train:${IMAGE_TAG}
          docker push $DOCKER_USERNAME/iris-mlflow:${IMAGE_TAG}

# # -----------------------
# # DEPLOY DEV
# # -----------------------
  deploy-dev:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Login Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u $DOCKER_USERNAME --password-stdin


      - name: Promote Image to TEST
        run: |
          docker pull $DOCKER_USERNAME/iris-api:${IMAGE_TAG}
          docker tag $DOCKER_USERNAME/iris-api:${IMAGE_TAG} $DOCKER_USERNAME/iris-api:dev
          docker push $DOCKER_USERNAME/iris-api:dev
          docker pull $DOCKER_USERNAME/iris-mlflow:${IMAGE_TAG}
          docker tag $DOCKER_USERNAME/iris-mlflow:${IMAGE_TAG} $DOCKER_USERNAME/iris-mlflow:dev
          docker push $DOCKER_USERNAME/iris-mlflow:dev
          docker pull $DOCKER_USERNAME/iris-train:${IMAGE_TAG}
          docker tag $DOCKER_USERNAME/iris-train:${IMAGE_TAG} $DOCKER_USERNAME/iris-train:dev
          docker push $DOCKER_USERNAME/iris-train:dev

      - name: Deploy to DEV
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/azureuser/MLOps-Regression_model
            git pull
            #export TAG=${{ github.sha }}
            docker-compose --env-file .env.dev -f docker-compose-base.yml -f docker-compose.prod.yml config
            docker-compose --env-file .env.dev -f docker-compose-base.yml -f docker-compose.prod.yml pull
            docker-compose --env-file .env.dev -f docker-compose-base.yml -f docker-compose.prod.yml up -d
            # docker-compose --env-file .env.dev pull
            # docker-compose --env-file .env.dev up -d

# # -----------------------
# # PROMOTE TO TEST
# # -----------------------
  promote-test:
    needs: deploy-dev
    runs-on: ubuntu-latest

    steps:
      - name: Login Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Promote Image to TEST
        run: |
          docker pull $DOCKER_USERNAME/iris-api:${IMAGE_TAG}
          docker tag $DOCKER_USERNAME/iris-api:${IMAGE_TAG} $DOCKER_USERNAME/iris-api:test
          docker push $DOCKER_USERNAME/iris-api:test

          docker pull $DOCKER_USERNAME/iris-train:${IMAGE_TAG}
          docker tag $DOCKER_USERNAME/iris-train:${IMAGE_TAG} $DOCKER_USERNAME/iris-train:test
          docker push $DOCKER_USERNAME/iris-train:test

# -----------------------
# DEPLOY TEST
# -----------------------
  deploy-test:
    needs: promote-test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to TEST
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TEST_VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/azureuser/MLOps-Regression_model
            export TAG=test
            docker-compose --env-file .env.tes -f docker-compose-base.yml -f docker-compose.prod.yml pull
            docker-compose --env-file .env.tes -f docker-compose-base.yml -f docker-compose.prod.yml up -d

# -----------------------
# PROMOTE TO PROD
# -----------------------
  promote-prod:
    needs: deploy-test
    runs-on: ubuntu-latest

    steps:
      - name: Login Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Promote Image to PROD
        run: |
          docker pull $DOCKER_USERNAME/iris-api:${IMAGE_TAG}
          docker tag $DOCKER_USERNAME/iris-api:${IMAGE_TAG} $DOCKER_USERNAME/iris-api:prod
          docker push $DOCKER_USERNAME/iris-api:prod

          docker pull $DOCKER_USERNAME/iris-train:${IMAGE_TAG}
          docker tag $DOCKER_USERNAME/iris-train:${IMAGE_TAG} $DOCKER_USERNAME/iris-train:prod
          docker push $DOCKER_USERNAME/iris-train:prod

# # -----------------------
# # DEPLOY PROD
# # -----------------------
  deploy-prod:
    needs: promote-prod
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to PROD
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/azureuser/MLOps-Regression_model
            export TAG=prod
            docker-compose --env-file .env.prod -f docker-compose-base.yml -f docker-compose.prod.yml pull
            docker-compose --env-file .env.prod -f docker-compose-base.yml -f docker-compose.prod.yml up -d